site_name: Bike Supply Chain

theme:
  name: material
  language: de
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    scheme: slate
    primary: blue
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - mermaid
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - content.code.copy
    - content.code.mermaid
nav:
  - Start: index.md
  - Einf√ºhrung: simulation-information.md
  - Berechnung:
    - Material Planung: calculations/material-planning.md
    - Arbeitsstationen: calculations/workplaces.md
    - Arbeitskosten: calculations/labour-costs.md
    - Produktions Planung: calculations/workstation_plan.md
  - Optimierung: optimization.md
  - Python: python-implementation.md
  - PDF: pdf.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - markdown_include.include:
      base_path: docs
  - attr_list

  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - def_list

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css